security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        backend_users: 
            memory: { users: 
                        { 
                            yaya: { password: '$2y$13$DKjLHro0ec2u5oHs5D9Zaez.kN6pIJ6tNKHjemEE1d0pTH7oThh5G', roles: ['ROLE_ADMIN'] }
                        }
                    }
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: backend_users

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall
            http_basic: true

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

            logout:
                path: app_logout

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/back/movie/add, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
